services:
    firefox:
        image: eecs388/firefox
        restart: always
        # Allocate sufficient memory to the Firefox GUI process.
        # If your machine is running out of memory, you might try decreasing this,
        # though Firefox may run into instability if you do so.
        shm_size: 2g
        # Access browser via http://localhost:38802 in your browser,
        # or by vnc://localhost:38852 in a VNC client.
        ports:
            - 38802:5800
            - 38852:5900
        volumes:
            - ..:/workspaces/project2
    stealer:
        build: .
        volumes:
            - ..:/workspaces/project2
        # Prevent container from instantly exiting, allowing us to attach terminal
        command: /bin/sh -c "sleep infinity"
